// Code generated by golazy. DO NOT EDIT.
package handler

import (
	"github.com/civet148/log"

	apiv1 "example/internal/handler/api/v1"
	"github.com/gin-gonic/gin"

	apiv1user "example/internal/handler/api/v1/user"

	apiv1ws "example/internal/handler/api/v1/ws"

	apiv1pay "example/internal/handler/api/v1/pay"

	_ "example/docs"
	"example/internal/middleware"
	"example/internal/svc"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func RegisterHandlers(server *gin.Engine, serverCtx *svc.ServiceContext) {
	gapiv1 := server.Group("/api/v1")
	gapiv1.Use(middleware.NewCorsMiddleware().Handle())
	gapiv1.Use(middleware.NewJwtAuthMiddleware().Handle())
	{
		gapiv1.POST("/sign_in", apiv1.UserSignInHandler(serverCtx))
		gapiv1.POST("/sign_up", apiv1.UserSignUpHandler(serverCtx))
		gapiv1.POST("/sign_out", apiv1.UserSignOutHandler(serverCtx))
	}

	gapiv1user := server.Group("/api/v1/user")
	gapiv1user.Use(middleware.NewValidatorMiddleware().Handle())
	{
		gapiv1user.GET("/list", apiv1user.GetUserListHandler(serverCtx))
		gapiv1user.PUT("/add", apiv1user.AddUserHandler(serverCtx))
		gapiv1user.POST("/edit", apiv1user.EditUserHandler(serverCtx))
		gapiv1user.DELETE("/delete", apiv1user.DeleteUserHandler(serverCtx))
		gapiv1user.GET("/:id", apiv1user.GetUserByIdHandler(serverCtx))
	}

	gapiv1ws := server.Group("/api/v1/ws")
	{
		gapiv1ws.GET("/market/list", apiv1ws.GetMarketListHandler(serverCtx))
	}

	gapiv1pay := server.Group("/api/v1/pay")
	{
		gapiv1pay.POST("/wechat/pay/{tid:[0-9]+}", apiv1pay.WechatPayCallbackHandler(serverCtx))
		gapiv1pay.POST("/wechat/refund/{tid:[0-9]+}", apiv1pay.WechatRefundCallbackHandler(serverCtx))
	}
	// add swagger route handler
	if serverCtx.Config.Mode == "dev" {
		server.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
		log.Infof("swagger running at http://%s:%v/swagger/index.html", serverCtx.Config.Host, serverCtx.Config.Port)
	}
}
